imports:
    - { resource: ../config.yml }
    - { resource: sulu.yml }
    - { resource: security.yml }
    - { resource: ../widgets.yml }

# Assetic Configuration
assetic:
    bundles:        [ ClientWebsiteBundle ]
