framework:
    router:
        resource: "%kernel.root_dir%/config/admin/routing.yml"
    session:
        save_path: "%kernel.cache_dir%/../../sessions/admin/%kernel.environment%"

# Doctrine Configuration
doctrine:
    orm:
        dql:
            string_functions:
                CAST: Sulu\Component\Rest\DQL\Cast

# Just a dirty hack to get the jms serializer bundle correctly working
# https://github.com/schmittjoh/JMSSerializerBundle/pull/270#issuecomment-21171800
parameters:
    jms_serializer.cache_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy

# Massive Build Configuration
massive_build:
    targets:
        prod:
            dependencies:
                database: ~
                phpcr: ~
                fixtures: ~
                phpcr_migrations: ~
        dev:
            dependencies:
                database: ~
                fixtures: ~
                phpcr: ~
                user: ~
                phpcr_migrations: ~
        maintain:
            dependencies:
                node_order:
                search_index:
                phpcr_migrations: ~

# Sulu Bundles
sulu_admin:
    name: %sulu_admin.name%
    email: %sulu_admin.email%

sulu_contact:
    form_of_address:
        male:
            id: 0
            name: male
            translation: contact.contacts.formOfAddress.male
        female:
            id: 1
            name: female
            translation: contact.contacts.formOfAddress.female

# SULU Resource Configuration
sulu_resource:
    contexts:
        contacts:
            fields: "/admin/api/contacts/fields"
            features:
                - "filters"
        accounts:
            fields: "/admin/api/accounts/fields"
            features:
                - "filters"
        tags:
            fields: "/admin/api/tags/fields"
            features:
                - "filters"
        roles:
            fields: "/admin/api/roles/fields"
            features:
                - "filters"
